# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[](bold red)"

# Disable the package module, hiding it from the prompt completely
[aws]
disabled = true
